# Generated by Django 5.2.14 on 2026-05-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='department',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
